# Configuration file for the rMATS Turbo snakemake pipeline

# Sample names and paths to BAM or FASTQ data files
SAMPLES:
    Hypoxia:
        - test/hypo_1.bam
        - test/hypo_2.bam
        - test/hypo_3.bam
    Normoxia:
        - test/norm_1.bam
        - test/norm_2.bam
        - test/norm_3.bam

# Paiwise comparisons to perform 
COMPARISONS:
    Hypoxia_v_Normoxia:  
        - "Hypoxia"
        - "Normoxia"
 
# Type of data: either "bam" for BAM files or "fastq" for FASTQ files.
DATA_TYPE:
    "bam"

# ---- required arguments passed to rMATS command ------

# Path to GTF file, an annotation of genes and transcripts
GTF_PATH:
    "test/hnrnph1.gtf"

# Path to the STAR binary indices that contains the SA file. (ONLY IF USING FASTQ)
STAR_INDEX:
    ""

# Length of each read
READ_LENGTH:
    150

# Number of threads to use for computation.
THREADS:
    1

# ----- end required args ---- 

# Additonal arguments to pass to rMATS command, supply as a single string
OPT_RMATS_ARGS:
    "--variable-read-length -t paired --libType fr-secondstrand --novelSS "

# Path to store intermediate files
TEMP_DIR:
    "test_results/temp"

# Path to the output directory
RESULT_PATH:
    "test_results"

# Container type, either singularity or docker
CONTAINER_TYPE:
    "singularity"

