shell.executable("/bin/bash")
shell.prefix("source ~/.bash_profile; ")
import os 

""" Snakefile for running 10x pipeline """

configfile: "config.yaml"

HAIRCUT_DATA = config["HAIRCUT_DATA"]
DATA = config["DATA"]
SAMPLES = config["HAIRCUT_SAMPLES"]
HAIRCUT_FASTA = config["HAIRCUT_FASTA"]
SRC = config["SRC"]

rule all:
    input:
      expand("{data}/fastqs/{sample}_{read_id}_umi.fastq.gz",
        data = DATA, sample = SAMPLES, read_id = ["R1", "R2"]),

      expand(os.path.join("{data}", "counts",
        "{sample}_umitools_counts.tsv.gz"),
        data = DATA, sample = SAMPLES),
      
      expand(os.path.join("{data}", "bam",
        "{sample}_haircut_umitagged_sorted.bam"),
         data = DATA, sample = SAMPLES),
        
      expand(os.path.join("{data}", "molecules",
        "{sample}", "{outfiles}"),
         data = DATA, sample = SAMPLES, 
         outfiles = ["molecules.tsv.gz", 
           "features.tsv", 
           "barcodes.tsv"]),
    
      expand(os.path.join("{data}", "counts",
        "{sample}_mtx", "{outfiles}"),
         data = DATA, sample = SAMPLES, 
         outfiles = ["matrix.mtx.gz", 
           "features.tsv", 
           "barcodes.tsv"]),

include: "rules/haircut_count.snake"
